[build-system]
requires = ["hatchling",
            "requests"]
build-backend = "hatchling.build"

[project]
name = "substack-api"
version = "0.0.2"
authors = [
    { name="Nick Hagar", email="nicholasrhagar@gmail.com" },
]
description = "The unofficial Substack API wrapper for Python."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/NHagar/substack_api"